Drop build-system group
we are using it to manage dependencies only right now, there is also
nothing to build here and trying to build causes a

```
RuntimeError: Building a package is not possible in non-package mode.
```